### PR TITLE
write_cout! fix

### LINKED ISSUE #202: Terminal::write -> Result<usize>
What's the purpose of the `usize` in the result? `std::io::stdout::flush` returns `Result<()>` and the `Terminal::write` always returns `Ok(0)` (in case there's no error). Am I overlooking something?

### PR DESCRIPTION
**Pull request by zrzka**
~**DON'T MERGE** as it needs to be rebased after all other PRs will be merged (if they will be) and there will be more occurrences of unused `std::io::Write` imports.~

* `write_cout!` returns number of written bytes
* `Terminal::write` returns number of written bytes (result of `write_cout!`)
* `execute!` macro is a bit simpler
* Remove unused `std::io::Write` imports

**NEW**

* Fixes rest of the `_cursor` & `_style` to make the `cargo test --all --exclude crossterm_winapi` pass (didn't check `_winapi` yet)

Fixes #202

### CODE REVIEW

**Comment by zrzka** [comment]
Or there's [2nd variant](https://github.com/TimonPost/crossterm/pull/212/commits/045fc650d4ac9ae85aea52d219819a1f3b1e200f) of the `write_cout!` which does use `write_all` instead of `write`.

The [1st variant](https://github.com/TimonPost/crossterm/pull/212/commits/173f205fabb7f9a70b288dba4635170e637aaa10) with `write` can fail, can write part of the buffer only, can return interrupted, which is not an error basically, etc.

File: crossterm_utils/src/macros.rs [hunk 1]
```diff
@@ -147,32 +150,25 @@ macro_rules! execute {
...
+                    if let Err(e) = write_cout!($write, $command.get_ansi_code()) {
+                        error = Some($crate::ErrorKind::from(e));
                     };
                 } else {
-                    match $command.execute_winapi() {
-                        Err(e) => {
-                            error = Some(Err($crate::ErrorKind::from(e)));
-                        }
-                        _ => {}
+                    if let Err(e) = $command.execute_winapi() {
```
Comment (TimonPost) [inline crossterm_utils/src/macros.rs]: Yea, definately better :)

**Comment by zrzka** [comment]
Yeah, still WIP. Waiting for other PRs to rebase & I didn't go through examples, etc. to check if there is/isn't an unused import.

**Comment by zrzka** [comment]
Will fix these conflicts with rebase when the #211 & #207 will be merged.

**Comment by zrzka** [comment]
@TimonPost rebased, added more _fixes_ (see first comment) and finally the whole `cargo test --all --exclude crossterm_winapi` is passing on my computer. Will continue with 2018 + examples collisions + other cleanup in another branch.

**Comment by TimonPost** [comment]
* `write_cout!` returns number of written bytes
* `Terminal::write` returns number of written bytes (result of `write_cout!`)
* `execute!` macro is a bit simpler
* Remove unused `std::io::Write` imports
